[app]
fast_llm = "gemini/gemini-2.0-flash-lite"
quality_llm = "gemini/gemini-2.0-flash"
vlm = "gemini/gemini-2.0-flash"
audio_lm = "gemini/gemini-2.0-flash-lite"

[completion]
provider = "r2r"
concurrent_request_limit = 16

[completion.generation_config]
temperature = 0.1
top_p = 1.0
max_tokens_to_sample = 4096
stream = false
add_generation_kwargs = {}

[database]
provider = "postgres"
user = "${R2R_POSTGRES_USER}"
password = "${R2R_POSTGRES_PASSWORD}"
host = "${R2R_POSTGRES_HOST}"
port = "${R2R_POSTGRES_PORT}"
db_name = "${R2R_POSTGRES_DBNAME}"
project_name = "${R2R_PROJECT_NAME}"

[auth]
provider = "supabase"

[filestorage]
provider = "s3"
endpoint_url = "${SUPABASE_STORAGE_ENDPOINT}"
bucket_name = "${SUPABASE_BUCKET_NAME}"
