[app]
quality_llm = "google/gemini-pro"
fast_llm = "google/gemini-pro"      # or "google/gemini-pro-vision" for vision tasks
reasoning_llm = "google/gemini-pro"
planning_llm = "google/gemini-pro"

[completion]
provider = "r2r"
concurrent_request_limit = 16 # Adjust to your infra/resources

[completion.generation_config]
temperature = 0.1
top_p = 1.0
max_tokens_to_sample = 4096
stream = false
add_generation_kwargs = {}

[database]
provider = "postgres"
user = "postgres"
password = "dag@13645440"
host = "bbzxfkkhuttmtwffdift.supabase.co"
port = 5432
db_name = "postgres"
project_name = "AwareeAI"

[auth]
provider = "supabase"

[filestorage]
provider = "s3"
endpoint_url = "https://bbzxfkkhuttmtwffdift.supabase.co/storage/v1/s3"
bucket_name = "aware-ai-bucket"
region_name = "us-east-2"
